export { activities } from './common/activities.schema';
export { duties } from './persons/duties.schema';
export { personsDuties } from './persons/persons-duties.schema';
export { personsHistory } from './persons/persons-history.schema';
export { personsRelations } from './persons/persons-relations.schema';
export { persons } from './persons/persons.schema';
export { relations } from './persons/relations.schema';
export { vehiclesTypes } from './persons/vehicle-types.schema';
export { vehiclesOwners } from './persons/vehicles-owners.schema';
export { vehicles } from './persons/vehicles.schema';
export { devices } from './users/devices.schema';
export { displayNames } from './users/display-names.schema';
export { emailCredentials } from './users/email-credentials.schema';
export { oldPasswords } from './users/old-passwords.schema';
export { otpTypes } from './users/otp-types.schema';
export { otps } from './users/otps.schema';
export { phoneDetails } from './users/phone-details.schema';
export { requests } from './users/requests.schema';
export { userSessions } from './users/user-sessions.schema';
export { userSettings } from './users/user-settings.schema';
export { usersHistory } from './users/users-history.schema';
export { users } from './users/users.schema';
export { verifications } from './users/verifications.schema';

// types
export type { IActivity } from './common/activities.schema';
export type { IDuty } from './persons/duties.schema';
export type { IPersonDuty } from './persons/persons-duties.schema';
export type { IPersonHistory } from './persons/persons-history.schema';
export type { IPersonRelation } from './persons/persons-relations.schema';
export type { IPerson } from './persons/persons.schema';
export type { IRelation } from './persons/relations.schema';
export type { IVehicleType } from './persons/vehicle-types.schema';
export type { IVehicleOwner } from './persons/vehicles-owners.schema';
export type { IVehicle } from './persons/vehicles.schema';
export type { IDevice } from './users/devices.schema';
export type { IDisplayName } from './users/display-names.schema';
export type { IEmailCredential } from './users/email-credentials.schema';
export type { IOldPassword } from './users/old-passwords.schema';
export type { IOTPType } from './users/otp-types.schema';
export type { IOTP } from './users/otps.schema';
export type { IPhoneDetails } from './users/phone-details.schema';
export type { IRequest } from './users/requests.schema';
export type { IUserSession } from './users/user-sessions.schema';
export type { IUserSetting } from './users/user-settings.schema';
export type { IUserHistory } from './users/users-history.schema';
export type { IUser } from './users/users.schema';
export type { IVerification } from './users/verifications.schema';
