import { createInsertSchema, createSelectSchema } from 'drizzle-zod';
import {
  activities,
  devices,
  displayNames,
  duties,
  emailCredentials,
  otpTypes,
  otps,
  persons,
  personsDuties,
  personsHistory,
  personsRelations,
  phoneDetails,
  relations,
  requests,
  userSessions,
  userSettings,
  users,
  usersHistory,
  vehicles,
  vehiclesOwners,
  vehiclesTypes,
  verifications,
} from './schema';

// export schemas
export {
  activities,
  devices,
  displayNames,
  duties,
  emailCredentials,
  otpTypes,
  otps,
  persons,
  personsDuties,
  personsHistory,
  personsRelations,
  phoneDetails,
  relations,
  requests,
  userSessions,
  userSettings,
  users,
  usersHistory,
  vehicles,
  vehiclesOwners,
  vehiclesTypes,
  verifications,
} from './schema';

// Insert schemas
export const insertSchema = {
  activities: createInsertSchema(activities),
  displayNames: createInsertSchema(displayNames),
  duties: createInsertSchema(duties),
  otpTypes: createInsertSchema(otpTypes),
  otps: createInsertSchema(otps),
  persons: createInsertSchema(persons),
  personsDuties: createInsertSchema(personsDuties),
  personsHistory: createInsertSchema(personsHistory),
  personsRelations: createInsertSchema(personsRelations),
  relations: createInsertSchema(relations),
  requests: createInsertSchema(requests),
  emailCredentials: createInsertSchema(emailCredentials),
  userSessions: createInsertSchema(userSessions),
  userSettings: createInsertSchema(userSettings),
  users: createInsertSchema(users),
  usersHistory: createInsertSchema(usersHistory),
  vehicles: createInsertSchema(vehicles),
  vehiclesOwners: createInsertSchema(vehiclesOwners),
  vehiclesTypes: createInsertSchema(vehiclesTypes),
  verifications: createInsertSchema(verifications),
  devices: createInsertSchema(devices),
  phoneDetails: createInsertSchema(phoneDetails),
};

// Select schemas
export const selectSchema = {
  activities: createSelectSchema(activities),
  displayNames: createSelectSchema(displayNames),
  duties: createSelectSchema(duties),
  otpTypes: createSelectSchema(otpTypes),
  otps: createSelectSchema(otps),
  persons: createSelectSchema(persons),
  personsDuties: createSelectSchema(personsDuties),
  personsHistory: createSelectSchema(personsHistory),
  personsRelations: createSelectSchema(personsRelations),
  relations: createSelectSchema(relations),
  requests: createSelectSchema(requests),
  emailCredentials: createSelectSchema(emailCredentials),
  userSessions: createSelectSchema(userSessions),
  userSettings: createSelectSchema(userSettings),
  users: createSelectSchema(users),
  usersHistory: createSelectSchema(usersHistory),
  vehicles: createSelectSchema(vehicles),
  vehiclesOwners: createSelectSchema(vehiclesOwners),
  vehiclesTypes: createSelectSchema(vehiclesTypes),
  verifications: createSelectSchema(verifications),
  devices: createSelectSchema(devices),
  phoneDetails: createSelectSchema(phoneDetails),
};
