export type {
  IActivity,
  IDevice,
  IDisplayName,
  IDuty,
  IEmailCredential,
  IEmailValidation,
  IOTP,
  IPerson,
  IPersonDuty,
  IPersonHistory,
  IPersonRelation,
  IPhoneDetails,
  IPhoneValidation,
  IRelation,
  IRequest,
  IToken,
  IUser,
  IUserHistory,
  IUserSession,
  IUserSetting,
  IVehicle,
  IVehicleOwner,
  IVehicleType,
  IVerification,
} from './schema';
